// src/app/app.component.ts
import { Component, computed, inject, signal, Signal } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { SelectInputComponent } from "./components/select-input/select-input.component";
import { ValueInputComponent } from "./components/value-input/value-input.component";
import { ChangeCurrencyService } from './service/change-currency.service';
import { DataStructure } from './model/data-structure';
import { DataUpdate } from './model/data-update';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, SelectInputComponent, ValueInputComponent],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})
export class AppComponent {
  private changeCurrencyService = inject(ChangeCurrencyService)
  public title: string = 'Currency Changer';
  private dataObject: DataUpdate = {
    currencyFrom: '',
    valueFrom: 0,
    currencyTo: '',
    valueto: 0,
    fieldUpdate: ''
  }

  updateValues(event: DataStructure) {
    this.dataObject[event.name] = event.value
    this.dataObject.fieldUpdate = event.name;
    this.changeCurrencyService.convertValue(this.dataObject)
  }
}

<div class="main">
  <h1 class="title">{{title}}</h1>
  <section class="changer-container">
    <div class="changer-content">
      <app-value-input class="changer-select-input" nameField="valueFrom"
        (valueInput)="updateValues($event)"></app-value-input>
      <app-select-input (valueSelected)="updateValues($event)" nameField="currencyFrom"></app-select-input>
    </div>
    <div class="equal-signal"> == </div>
    <div class="changer-content">
      <app-value-input class="changer-select-input" nameField="valueTo"
        (valueInput)="updateValues($event)"></app-value-input>
      <app-select-input (valueSelected)="updateValues($event)" nameField="currencyTo"></app-select-input>
    </div>
  </section>

</div>

<router-outlet />

// react-project/src/App.tsx
import React, { useState } from 'react';
import './App.css';
import SelectInput from './components/select-input';
import ValueInput from './components/value-input';
import CalculateCurrency from './service/calculate-currency';
import { DataUpdate } from './model/data-update';

function App() {
  const title: string = 'Currency Changer';
  const [values, setValues] = useState<DataUpdate>({
    currencyTo: '',
    valueTo: 0,
    currencyFrom: '',
    valueFrom: 0,
    fieldUpdate: ''
  })

  const updateValues = async (value: string, nameField: string) => {
    setValues({ ...values, nameField: value, fieldUpdate: nameField })
    values[nameField] = value;
    values.fieldUpdate = nameField;
    const result: DataUpdate = await CalculateCurrency(values);
    setValues(result);
  }

  return (
    <div className="App">
      <h1 className="title">{title}</h1>
      <section className="changer-container">
        <div className="changer-content">
          <SelectInput value={values.currencyFrom} onChange={(value: string) => updateValues(value, "currencyFrom")}></SelectInput>
          <ValueInput value={values.valueFrom} onChange={(value: string) => updateValues(value, "valueFrom")}></ValueInput>
        </div >
        <div className="equal-signal"> == </div>
        <div className="changer-content">
          <SelectInput value={values.currencyTo} onChange={(value: string) => updateValues(value, "currencyTo")}></SelectInput>
          <ValueInput value={values.valueTo} onChange={(value: string) => updateValues(value, "valueTo")}></ValueInput>
        </div >
      </section >
    </div >

  );
}

export default App;
