// src/app/components/select-input/select-input.component.ts
import { NgFor } from '@angular/common';
import { Component, EventEmitter, Output } from '@angular/core';

@Component({
  selector: 'app-select-input',
  standalone: true,
  imports: [NgFor],
  templateUrl: './select-input.component.html',
  styleUrl: './select-input.component.scss'
})
export class SelectInputComponent {
  @Output() valueSelected = new EventEmitter<string>();

  // get this list from outside
  public list: Array<string> = [
    'USD',
    'BRL',
    'GBR',
    'EUR'
  ]

  onSelected(value: string) {
    this.valueSelected.emit(value)
  }
}

<select #element (change)="onSelected(element.value)">
  <option [value]="" selected>-</option>
  <option *ngFor="let item of list" [value]="item">{{item}}</option>
</select>

// react-project/src/components/select-input/index.tsx
const SelectInput = () => {
    const list: Array<string> = [
        'USD',
        'BRL',
        'EUR'
    ]

    return (
        <select>
            <option value="" selected > - </option>
            {
                list.map((e: string) => <option value={e} > {e}</option>)
            }
        </select>
    )
}

export default SelectInput;
